server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: demo-redis-pub-sub
  redis:
    database: 0
    host: localhost
    port: 49153
    timeout: 60000
    username: default
    password: redispw

logging:
  level:
    com.example.demoredispubsub: DEBUG